/**
 * <p> 
 * Copyright (C) IBALIFE Software Co.,Ltd.
 * </p>
 * <p>
 * 创建日期： 2017-11-14
 * </p>
 */
package cn.liuyiyou.web.model;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;

/**
 * 数据表 <code>user</code> 的动态查询条件
 * <p>
 * 创建日期： 2017-11-14
 * </p>
 */
public class UserExample {

    /** 分页页数，user */
    protected int page;

    /** 分页条数，user */
    protected int pageSize;

    /** 排序字段，user */
    protected String orderByClause;

    /** 是否过滤重复数据，user */
    protected boolean distinct;

    /** 动态查询条件列表，user */
    protected List<Criteria> oredCriteria;

    /**
     * 设置当前页，user
     *
     * @param page 分页对象
     */
    public void setPage(int page) {
        this.page = page;
    }

    /**
     * 获取页数，user
     *
     */
    public int getPage() {
        return page;
    }

    /**
     * 设置每页条数，user
     *
     * @param pageSize This parameter was generated by MyBatis Generator
     */
    public void setPageSize(int pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * 获取当页字段，user
     *
     */
    public int getPageSize() {
        return pageSize;
    }

    /**
     * 构造查询条件，user
     *
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * 设置排序字段，user
     *
     * @param orderByClause 排序字段
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * 获取排序字段，user
     *
     * @return 排序字段
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * 设置过滤重复数据，user
     *
     * @param distinct 是否过滤重复数据
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * 是否过滤重复数据，user
     *
     * @return 需要过滤重复数据时，返回 true，否则返回 false
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * 获取当前的查询条件实例，user
     *
     * @return 当前的查询条件实例
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * 增加或者的查询条件,用于构建或者查询，user
     *
     * @param criteria 过滤条件实例
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * 创建一个新的或者查询条件，user
     *
     * @return 查询条件
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * 创建一个查询条件，user
     *
     * @return 新创建的查询条件
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.isEmpty()) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * 内部构建查询条件对象，user
     *
     * @return 查询条件
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * 清除查询条件，user
     *
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * 基本动态 SQL 对象，user
     */
    public abstract static class GeneratedCriteria {

        protected List<Criterion> criteria;

        public GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Integer value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Integer value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Integer value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Integer value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Integer value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Integer> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Integer> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Integer value1, Integer value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Integer value1, Integer value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andAccountIsNull() {
            addCriterion("account is null");
            return (Criteria) this;
        }

        public Criteria andAccountIsNotNull() {
            addCriterion("account is not null");
            return (Criteria) this;
        }

        public Criteria andAccountEqualTo(String value) {
            addCriterion("account =", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotEqualTo(String value) {
            addCriterion("account <>", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountGreaterThan(String value) {
            addCriterion("account >", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountGreaterThanOrEqualTo(String value) {
            addCriterion("account >=", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLessThan(String value) {
            addCriterion("account <", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLessThanOrEqualTo(String value) {
            addCriterion("account <=", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLike(String value) {
            addCriterion("account like", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotLike(String value) {
            addCriterion("account not like", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountIn(List<String> values) {
            addCriterion("account in", values, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotIn(List<String> values) {
            addCriterion("account not in", values, "account");
            return (Criteria) this;
        }

        public Criteria andAccountBetween(String value1, String value2) {
            addCriterion("account between", value1, value2, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotBetween(String value1, String value2) {
            addCriterion("account not between", value1, value2, "account");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNull() {
            addCriterion("real_name is null");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNotNull() {
            addCriterion("real_name is not null");
            return (Criteria) this;
        }

        public Criteria andRealNameEqualTo(String value) {
            addCriterion("real_name =", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotEqualTo(String value) {
            addCriterion("real_name <>", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThan(String value) {
            addCriterion("real_name >", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThanOrEqualTo(String value) {
            addCriterion("real_name >=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThan(String value) {
            addCriterion("real_name <", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThanOrEqualTo(String value) {
            addCriterion("real_name <=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLike(String value) {
            addCriterion("real_name like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotLike(String value) {
            addCriterion("real_name not like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameIn(List<String> values) {
            addCriterion("real_name in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotIn(List<String> values) {
            addCriterion("real_name not in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameBetween(String value1, String value2) {
            addCriterion("real_name between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotBetween(String value1, String value2) {
            addCriterion("real_name not between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNull() {
            addCriterion("nickname is null");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNotNull() {
            addCriterion("nickname is not null");
            return (Criteria) this;
        }

        public Criteria andNicknameEqualTo(String value) {
            addCriterion("nickname =", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotEqualTo(String value) {
            addCriterion("nickname <>", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThan(String value) {
            addCriterion("nickname >", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("nickname >=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThan(String value) {
            addCriterion("nickname <", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThanOrEqualTo(String value) {
            addCriterion("nickname <=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLike(String value) {
            addCriterion("nickname like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotLike(String value) {
            addCriterion("nickname not like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameIn(List<String> values) {
            addCriterion("nickname in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotIn(List<String> values) {
            addCriterion("nickname not in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameBetween(String value1, String value2) {
            addCriterion("nickname between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotBetween(String value1, String value2) {
            addCriterion("nickname not between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andPasswdIsNull() {
            addCriterion("passwd is null");
            return (Criteria) this;
        }

        public Criteria andPasswdIsNotNull() {
            addCriterion("passwd is not null");
            return (Criteria) this;
        }

        public Criteria andPasswdEqualTo(String value) {
            addCriterion("passwd =", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotEqualTo(String value) {
            addCriterion("passwd <>", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdGreaterThan(String value) {
            addCriterion("passwd >", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdGreaterThanOrEqualTo(String value) {
            addCriterion("passwd >=", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdLessThan(String value) {
            addCriterion("passwd <", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdLessThanOrEqualTo(String value) {
            addCriterion("passwd <=", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdLike(String value) {
            addCriterion("passwd like", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotLike(String value) {
            addCriterion("passwd not like", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdIn(List<String> values) {
            addCriterion("passwd in", values, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotIn(List<String> values) {
            addCriterion("passwd not in", values, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdBetween(String value1, String value2) {
            addCriterion("passwd between", value1, value2, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotBetween(String value1, String value2) {
            addCriterion("passwd not between", value1, value2, "passwd");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateChannelIsNull() {
            addCriterion("create_channel is null");
            return (Criteria) this;
        }

        public Criteria andCreateChannelIsNotNull() {
            addCriterion("create_channel is not null");
            return (Criteria) this;
        }

        public Criteria andCreateChannelEqualTo(Byte value) {
            addCriterion("create_channel =", value, "createChannel");
            return (Criteria) this;
        }

        public Criteria andCreateChannelNotEqualTo(Byte value) {
            addCriterion("create_channel <>", value, "createChannel");
            return (Criteria) this;
        }

        public Criteria andCreateChannelGreaterThan(Byte value) {
            addCriterion("create_channel >", value, "createChannel");
            return (Criteria) this;
        }

        public Criteria andCreateChannelGreaterThanOrEqualTo(Byte value) {
            addCriterion("create_channel >=", value, "createChannel");
            return (Criteria) this;
        }

        public Criteria andCreateChannelLessThan(Byte value) {
            addCriterion("create_channel <", value, "createChannel");
            return (Criteria) this;
        }

        public Criteria andCreateChannelLessThanOrEqualTo(Byte value) {
            addCriterion("create_channel <=", value, "createChannel");
            return (Criteria) this;
        }

        public Criteria andCreateChannelIn(List<Byte> values) {
            addCriterion("create_channel in", values, "createChannel");
            return (Criteria) this;
        }

        public Criteria andCreateChannelNotIn(List<Byte> values) {
            addCriterion("create_channel not in", values, "createChannel");
            return (Criteria) this;
        }

        public Criteria andCreateChannelBetween(Byte value1, Byte value2) {
            addCriterion("create_channel between", value1, value2, "createChannel");
            return (Criteria) this;
        }

        public Criteria andCreateChannelNotBetween(Byte value1, Byte value2) {
            addCriterion("create_channel not between", value1, value2, "createChannel");
            return (Criteria) this;
        }

        public Criteria andLastTimeIsNull() {
            addCriterion("last_time is null");
            return (Criteria) this;
        }

        public Criteria andLastTimeIsNotNull() {
            addCriterion("last_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastTimeEqualTo(Date value) {
            addCriterion("last_time =", value, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeNotEqualTo(Date value) {
            addCriterion("last_time <>", value, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeGreaterThan(Date value) {
            addCriterion("last_time >", value, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_time >=", value, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeLessThan(Date value) {
            addCriterion("last_time <", value, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_time <=", value, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeIn(List<Date> values) {
            addCriterion("last_time in", values, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeNotIn(List<Date> values) {
            addCriterion("last_time not in", values, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeBetween(Date value1, Date value2) {
            addCriterion("last_time between", value1, value2, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_time not between", value1, value2, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastChannelIsNull() {
            addCriterion("last_channel is null");
            return (Criteria) this;
        }

        public Criteria andLastChannelIsNotNull() {
            addCriterion("last_channel is not null");
            return (Criteria) this;
        }

        public Criteria andLastChannelEqualTo(Byte value) {
            addCriterion("last_channel =", value, "lastChannel");
            return (Criteria) this;
        }

        public Criteria andLastChannelNotEqualTo(Byte value) {
            addCriterion("last_channel <>", value, "lastChannel");
            return (Criteria) this;
        }

        public Criteria andLastChannelGreaterThan(Byte value) {
            addCriterion("last_channel >", value, "lastChannel");
            return (Criteria) this;
        }

        public Criteria andLastChannelGreaterThanOrEqualTo(Byte value) {
            addCriterion("last_channel >=", value, "lastChannel");
            return (Criteria) this;
        }

        public Criteria andLastChannelLessThan(Byte value) {
            addCriterion("last_channel <", value, "lastChannel");
            return (Criteria) this;
        }

        public Criteria andLastChannelLessThanOrEqualTo(Byte value) {
            addCriterion("last_channel <=", value, "lastChannel");
            return (Criteria) this;
        }

        public Criteria andLastChannelIn(List<Byte> values) {
            addCriterion("last_channel in", values, "lastChannel");
            return (Criteria) this;
        }

        public Criteria andLastChannelNotIn(List<Byte> values) {
            addCriterion("last_channel not in", values, "lastChannel");
            return (Criteria) this;
        }

        public Criteria andLastChannelBetween(Byte value1, Byte value2) {
            addCriterion("last_channel between", value1, value2, "lastChannel");
            return (Criteria) this;
        }

        public Criteria andLastChannelNotBetween(Byte value1, Byte value2) {
            addCriterion("last_channel not between", value1, value2, "lastChannel");
            return (Criteria) this;
        }

        public Criteria andLastIpIsNull() {
            addCriterion("last_ip is null");
            return (Criteria) this;
        }

        public Criteria andLastIpIsNotNull() {
            addCriterion("last_ip is not null");
            return (Criteria) this;
        }

        public Criteria andLastIpEqualTo(String value) {
            addCriterion("last_ip =", value, "lastIp");
            return (Criteria) this;
        }

        public Criteria andLastIpNotEqualTo(String value) {
            addCriterion("last_ip <>", value, "lastIp");
            return (Criteria) this;
        }

        public Criteria andLastIpGreaterThan(String value) {
            addCriterion("last_ip >", value, "lastIp");
            return (Criteria) this;
        }

        public Criteria andLastIpGreaterThanOrEqualTo(String value) {
            addCriterion("last_ip >=", value, "lastIp");
            return (Criteria) this;
        }

        public Criteria andLastIpLessThan(String value) {
            addCriterion("last_ip <", value, "lastIp");
            return (Criteria) this;
        }

        public Criteria andLastIpLessThanOrEqualTo(String value) {
            addCriterion("last_ip <=", value, "lastIp");
            return (Criteria) this;
        }

        public Criteria andLastIpLike(String value) {
            addCriterion("last_ip like", value, "lastIp");
            return (Criteria) this;
        }

        public Criteria andLastIpNotLike(String value) {
            addCriterion("last_ip not like", value, "lastIp");
            return (Criteria) this;
        }

        public Criteria andLastIpIn(List<String> values) {
            addCriterion("last_ip in", values, "lastIp");
            return (Criteria) this;
        }

        public Criteria andLastIpNotIn(List<String> values) {
            addCriterion("last_ip not in", values, "lastIp");
            return (Criteria) this;
        }

        public Criteria andLastIpBetween(String value1, String value2) {
            addCriterion("last_ip between", value1, value2, "lastIp");
            return (Criteria) this;
        }

        public Criteria andLastIpNotBetween(String value1, String value2) {
            addCriterion("last_ip not between", value1, value2, "lastIp");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andUserTypeIsNull() {
            addCriterion("user_type is null");
            return (Criteria) this;
        }

        public Criteria andUserTypeIsNotNull() {
            addCriterion("user_type is not null");
            return (Criteria) this;
        }

        public Criteria andUserTypeEqualTo(Byte value) {
            addCriterion("user_type =", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotEqualTo(Byte value) {
            addCriterion("user_type <>", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeGreaterThan(Byte value) {
            addCriterion("user_type >", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("user_type >=", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLessThan(Byte value) {
            addCriterion("user_type <", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLessThanOrEqualTo(Byte value) {
            addCriterion("user_type <=", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeIn(List<Byte> values) {
            addCriterion("user_type in", values, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotIn(List<Byte> values) {
            addCriterion("user_type not in", values, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeBetween(Byte value1, Byte value2) {
            addCriterion("user_type between", value1, value2, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("user_type not between", value1, value2, "userType");
            return (Criteria) this;
        }

        public Criteria andInvCodeIsNull() {
            addCriterion("inv_code is null");
            return (Criteria) this;
        }

        public Criteria andInvCodeIsNotNull() {
            addCriterion("inv_code is not null");
            return (Criteria) this;
        }

        public Criteria andInvCodeEqualTo(String value) {
            addCriterion("inv_code =", value, "invCode");
            return (Criteria) this;
        }

        public Criteria andInvCodeNotEqualTo(String value) {
            addCriterion("inv_code <>", value, "invCode");
            return (Criteria) this;
        }

        public Criteria andInvCodeGreaterThan(String value) {
            addCriterion("inv_code >", value, "invCode");
            return (Criteria) this;
        }

        public Criteria andInvCodeGreaterThanOrEqualTo(String value) {
            addCriterion("inv_code >=", value, "invCode");
            return (Criteria) this;
        }

        public Criteria andInvCodeLessThan(String value) {
            addCriterion("inv_code <", value, "invCode");
            return (Criteria) this;
        }

        public Criteria andInvCodeLessThanOrEqualTo(String value) {
            addCriterion("inv_code <=", value, "invCode");
            return (Criteria) this;
        }

        public Criteria andInvCodeLike(String value) {
            addCriterion("inv_code like", value, "invCode");
            return (Criteria) this;
        }

        public Criteria andInvCodeNotLike(String value) {
            addCriterion("inv_code not like", value, "invCode");
            return (Criteria) this;
        }

        public Criteria andInvCodeIn(List<String> values) {
            addCriterion("inv_code in", values, "invCode");
            return (Criteria) this;
        }

        public Criteria andInvCodeNotIn(List<String> values) {
            addCriterion("inv_code not in", values, "invCode");
            return (Criteria) this;
        }

        public Criteria andInvCodeBetween(String value1, String value2) {
            addCriterion("inv_code between", value1, value2, "invCode");
            return (Criteria) this;
        }

        public Criteria andInvCodeNotBetween(String value1, String value2) {
            addCriterion("inv_code not between", value1, value2, "invCode");
            return (Criteria) this;
        }

        public Criteria andSrcIsNull() {
            addCriterion("src is null");
            return (Criteria) this;
        }

        public Criteria andSrcIsNotNull() {
            addCriterion("src is not null");
            return (Criteria) this;
        }

        public Criteria andSrcEqualTo(Byte value) {
            addCriterion("src =", value, "src");
            return (Criteria) this;
        }

        public Criteria andSrcNotEqualTo(Byte value) {
            addCriterion("src <>", value, "src");
            return (Criteria) this;
        }

        public Criteria andSrcGreaterThan(Byte value) {
            addCriterion("src >", value, "src");
            return (Criteria) this;
        }

        public Criteria andSrcGreaterThanOrEqualTo(Byte value) {
            addCriterion("src >=", value, "src");
            return (Criteria) this;
        }

        public Criteria andSrcLessThan(Byte value) {
            addCriterion("src <", value, "src");
            return (Criteria) this;
        }

        public Criteria andSrcLessThanOrEqualTo(Byte value) {
            addCriterion("src <=", value, "src");
            return (Criteria) this;
        }

        public Criteria andSrcIn(List<Byte> values) {
            addCriterion("src in", values, "src");
            return (Criteria) this;
        }

        public Criteria andSrcNotIn(List<Byte> values) {
            addCriterion("src not in", values, "src");
            return (Criteria) this;
        }

        public Criteria andSrcBetween(Byte value1, Byte value2) {
            addCriterion("src between", value1, value2, "src");
            return (Criteria) this;
        }

        public Criteria andSrcNotBetween(Byte value1, Byte value2) {
            addCriterion("src not between", value1, value2, "src");
            return (Criteria) this;
        }

        public Criteria andDitchIsNull() {
            addCriterion("ditch is null");
            return (Criteria) this;
        }

        public Criteria andDitchIsNotNull() {
            addCriterion("ditch is not null");
            return (Criteria) this;
        }

        public Criteria andDitchEqualTo(Integer value) {
            addCriterion("ditch =", value, "ditch");
            return (Criteria) this;
        }

        public Criteria andDitchNotEqualTo(Integer value) {
            addCriterion("ditch <>", value, "ditch");
            return (Criteria) this;
        }

        public Criteria andDitchGreaterThan(Integer value) {
            addCriterion("ditch >", value, "ditch");
            return (Criteria) this;
        }

        public Criteria andDitchGreaterThanOrEqualTo(Integer value) {
            addCriterion("ditch >=", value, "ditch");
            return (Criteria) this;
        }

        public Criteria andDitchLessThan(Integer value) {
            addCriterion("ditch <", value, "ditch");
            return (Criteria) this;
        }

        public Criteria andDitchLessThanOrEqualTo(Integer value) {
            addCriterion("ditch <=", value, "ditch");
            return (Criteria) this;
        }

        public Criteria andDitchIn(List<Integer> values) {
            addCriterion("ditch in", values, "ditch");
            return (Criteria) this;
        }

        public Criteria andDitchNotIn(List<Integer> values) {
            addCriterion("ditch not in", values, "ditch");
            return (Criteria) this;
        }

        public Criteria andDitchBetween(Integer value1, Integer value2) {
            addCriterion("ditch between", value1, value2, "ditch");
            return (Criteria) this;
        }

        public Criteria andDitchNotBetween(Integer value1, Integer value2) {
            addCriterion("ditch not between", value1, value2, "ditch");
            return (Criteria) this;
        }

        public Criteria andConsumeIsNull() {
            addCriterion("consume is null");
            return (Criteria) this;
        }

        public Criteria andConsumeIsNotNull() {
            addCriterion("consume is not null");
            return (Criteria) this;
        }

        public Criteria andConsumeEqualTo(Boolean value) {
            addCriterion("consume =", value, "consume");
            return (Criteria) this;
        }

        public Criteria andConsumeNotEqualTo(Boolean value) {
            addCriterion("consume <>", value, "consume");
            return (Criteria) this;
        }

        public Criteria andConsumeGreaterThan(Boolean value) {
            addCriterion("consume >", value, "consume");
            return (Criteria) this;
        }

        public Criteria andConsumeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("consume >=", value, "consume");
            return (Criteria) this;
        }

        public Criteria andConsumeLessThan(Boolean value) {
            addCriterion("consume <", value, "consume");
            return (Criteria) this;
        }

        public Criteria andConsumeLessThanOrEqualTo(Boolean value) {
            addCriterion("consume <=", value, "consume");
            return (Criteria) this;
        }

        public Criteria andConsumeIn(List<Boolean> values) {
            addCriterion("consume in", values, "consume");
            return (Criteria) this;
        }

        public Criteria andConsumeNotIn(List<Boolean> values) {
            addCriterion("consume not in", values, "consume");
            return (Criteria) this;
        }

        public Criteria andConsumeBetween(Boolean value1, Boolean value2) {
            addCriterion("consume between", value1, value2, "consume");
            return (Criteria) this;
        }

        public Criteria andConsumeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("consume not between", value1, value2, "consume");
            return (Criteria) this;
        }

        public Criteria andOwerShipIsNull() {
            addCriterion("ower_ship is null");
            return (Criteria) this;
        }

        public Criteria andOwerShipIsNotNull() {
            addCriterion("ower_ship is not null");
            return (Criteria) this;
        }

        public Criteria andOwerShipEqualTo(String value) {
            addCriterion("ower_ship =", value, "owerShip");
            return (Criteria) this;
        }

        public Criteria andOwerShipNotEqualTo(String value) {
            addCriterion("ower_ship <>", value, "owerShip");
            return (Criteria) this;
        }

        public Criteria andOwerShipGreaterThan(String value) {
            addCriterion("ower_ship >", value, "owerShip");
            return (Criteria) this;
        }

        public Criteria andOwerShipGreaterThanOrEqualTo(String value) {
            addCriterion("ower_ship >=", value, "owerShip");
            return (Criteria) this;
        }

        public Criteria andOwerShipLessThan(String value) {
            addCriterion("ower_ship <", value, "owerShip");
            return (Criteria) this;
        }

        public Criteria andOwerShipLessThanOrEqualTo(String value) {
            addCriterion("ower_ship <=", value, "owerShip");
            return (Criteria) this;
        }

        public Criteria andOwerShipLike(String value) {
            addCriterion("ower_ship like", value, "owerShip");
            return (Criteria) this;
        }

        public Criteria andOwerShipNotLike(String value) {
            addCriterion("ower_ship not like", value, "owerShip");
            return (Criteria) this;
        }

        public Criteria andOwerShipIn(List<String> values) {
            addCriterion("ower_ship in", values, "owerShip");
            return (Criteria) this;
        }

        public Criteria andOwerShipNotIn(List<String> values) {
            addCriterion("ower_ship not in", values, "owerShip");
            return (Criteria) this;
        }

        public Criteria andOwerShipBetween(String value1, String value2) {
            addCriterion("ower_ship between", value1, value2, "owerShip");
            return (Criteria) this;
        }

        public Criteria andOwerShipNotBetween(String value1, String value2) {
            addCriterion("ower_ship not between", value1, value2, "owerShip");
            return (Criteria) this;
        }

        public Criteria andUidIn(Integer ... values) {
            return andUidIn(Arrays.asList(values));
        }

        public Criteria andUidNotIn(Integer ... values) {
            return andUidNotIn(Arrays.asList(values));
        }

        public Criteria andAccountIn(String ... values) {
            return andAccountIn(Arrays.asList(values));
        }

        public Criteria andAccountNotIn(String ... values) {
            return andAccountNotIn(Arrays.asList(values));
        }

        public Criteria andRealNameIn(String ... values) {
            return andRealNameIn(Arrays.asList(values));
        }

        public Criteria andRealNameNotIn(String ... values) {
            return andRealNameNotIn(Arrays.asList(values));
        }

        public Criteria andNicknameIn(String ... values) {
            return andNicknameIn(Arrays.asList(values));
        }

        public Criteria andNicknameNotIn(String ... values) {
            return andNicknameNotIn(Arrays.asList(values));
        }

        public Criteria andPasswdIn(String ... values) {
            return andPasswdIn(Arrays.asList(values));
        }

        public Criteria andPasswdNotIn(String ... values) {
            return andPasswdNotIn(Arrays.asList(values));
        }

        public Criteria andEmailIn(String ... values) {
            return andEmailIn(Arrays.asList(values));
        }

        public Criteria andEmailNotIn(String ... values) {
            return andEmailNotIn(Arrays.asList(values));
        }

        public Criteria andCreateTimeIn(Date ... values) {
            return andCreateTimeIn(Arrays.asList(values));
        }

        public Criteria andCreateTimeNotIn(Date ... values) {
            return andCreateTimeNotIn(Arrays.asList(values));
        }

        public Criteria andCreateChannelIn(Byte ... values) {
            return andCreateChannelIn(Arrays.asList(values));
        }

        public Criteria andCreateChannelNotIn(Byte ... values) {
            return andCreateChannelNotIn(Arrays.asList(values));
        }

        public Criteria andLastTimeIn(Date ... values) {
            return andLastTimeIn(Arrays.asList(values));
        }

        public Criteria andLastTimeNotIn(Date ... values) {
            return andLastTimeNotIn(Arrays.asList(values));
        }

        public Criteria andLastChannelIn(Byte ... values) {
            return andLastChannelIn(Arrays.asList(values));
        }

        public Criteria andLastChannelNotIn(Byte ... values) {
            return andLastChannelNotIn(Arrays.asList(values));
        }

        public Criteria andLastIpIn(String ... values) {
            return andLastIpIn(Arrays.asList(values));
        }

        public Criteria andLastIpNotIn(String ... values) {
            return andLastIpNotIn(Arrays.asList(values));
        }

        public Criteria andStatusIn(Byte ... values) {
            return andStatusIn(Arrays.asList(values));
        }

        public Criteria andStatusNotIn(Byte ... values) {
            return andStatusNotIn(Arrays.asList(values));
        }

        public Criteria andUserTypeIn(Byte ... values) {
            return andUserTypeIn(Arrays.asList(values));
        }

        public Criteria andUserTypeNotIn(Byte ... values) {
            return andUserTypeNotIn(Arrays.asList(values));
        }

        public Criteria andInvCodeIn(String ... values) {
            return andInvCodeIn(Arrays.asList(values));
        }

        public Criteria andInvCodeNotIn(String ... values) {
            return andInvCodeNotIn(Arrays.asList(values));
        }

        public Criteria andSrcIn(Byte ... values) {
            return andSrcIn(Arrays.asList(values));
        }

        public Criteria andSrcNotIn(Byte ... values) {
            return andSrcNotIn(Arrays.asList(values));
        }

        public Criteria andDitchIn(Integer ... values) {
            return andDitchIn(Arrays.asList(values));
        }

        public Criteria andDitchNotIn(Integer ... values) {
            return andDitchNotIn(Arrays.asList(values));
        }

        public Criteria andConsumeIn(Boolean ... values) {
            return andConsumeIn(Arrays.asList(values));
        }

        public Criteria andConsumeNotIn(Boolean ... values) {
            return andConsumeNotIn(Arrays.asList(values));
        }

        public Criteria andOwerShipIn(String ... values) {
            return andOwerShipIn(Arrays.asList(values));
        }

        public Criteria andOwerShipNotIn(String ... values) {
            return andOwerShipNotIn(Arrays.asList(values));
        }
    }

    /**
     *  数据表 <code>user</code> 对应的 Java 实体类
     */
    public static class Criteria extends GeneratedCriteria {


        public Criteria() {
            super();
        }
    }

    /**
     * 动态 SQL 对象，user
     */
    public static class Criterion {

        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        public Criterion() {
            super();
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}