/**
 * <p> 
 * Copyright (C) IBALIFE Software Co.,Ltd.
 * </p>
 * <p>
 * 创建日期： 2017-11-17
 * </p>
 */
package cn.liuyiyou.web.mapper;

import cn.liuyiyou.web.model.Blog;
import com.github.pagehelper.PageInfo;

import java.util.List;

/**
 * <code>t_blog</code>的 MyBatis Mapper 接口<br>
 * 对应的数据表为 <code>t_blog</code>
 * <p>
 * 创建日期： 2017-11-17
 * </p>
 */
public interface BlogMapper {

    /**
     * 根据主键删除数据库的记录，t_blog
     *
     * @param id 主键
     * @return 删除的数据记录条数
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * 将数据记录插入数据库，t_blog
     *
     * @param record 数据记录
     * @return 新插入的数据对象
     */
    int insert(Blog record);

    /**
     * 将数据记录中值不为 <code>null</code> 的字段写入数据库，t_blog
     *
     * @param record 数据记录
     * @return 新插入的数据对象
     */
    int insertSelective(Blog record);

    /**
     * 根据指定主键获取一条数据记录，t_blog
     *
     * @param id 主键
     * @return 对应的数据记录
     */
    Blog selectByPrimaryKey(Integer id);

    /**
     * 动态字段，根据主键来更新符合条件的数据记录，t_blog
     *
     * @param record 数据记录
     * @return 更新后的数据对象
     */
    int updateByPrimaryKeySelective(Blog record);

    /**
     * This method was generated by MyBatis Generator，t_blog
     *
     * @param record 数据记录
     */
    int updateByPrimaryKeyWithBLOBs(Blog record);

    /**
     * 根据主键来更新符合条件的数据记录，t_blog
     *
     * @param record 数据记录
     * @return 更新后的数据对象
     */
    int updateByPrimaryKey(Blog record);

    /**
     * This method was generated by MyBatis Generator，t_blog
     *
     * @param record 数据记录
     */
    List<Blog> selectByParams(Blog record);


    /**
     * 得到博客以及所带的标签
     * @param params
     * @return
     */
    List<Blog> selectBlogPageWithTags(Blog params);
}