/**
 * <p> 
 * Copyright (C) IBALIFE Software Co.,Ltd.
 * </p>
 * <p>
 * 创建日期： 2017-11-17
 * </p>
 */
package cn.liuyiyou.web.mapper;

import cn.liuyiyou.web.model.Message;
import java.util.List;

/**
 * 短消息的 MyBatis Mapper 接口<br>
 * 对应的数据表为 <code>t_message</code>
 * <p>
 * 创建日期： 2017-11-17
 * </p>
 */
public interface MessageMapper {

    /**
     * 根据主键删除数据库的记录，t_message
     *
     * @param msgId This parameter was generated by MyBatis Generator
     * @return 删除的数据记录条数
     */
    int deleteByPrimaryKey(Integer msgId);

    /**
     * 将数据记录插入数据库，t_message
     *
     * @param record 数据记录
     * @return 新插入的数据对象
     */
    int insert(Message record);

    /**
     * 将数据记录中值不为 <code>null</code> 的字段写入数据库，t_message
     *
     * @param record 数据记录
     * @return 新插入的数据对象
     */
    int insertSelective(Message record);

    /**
     * 根据指定主键获取一条数据记录，t_message
     *
     * @param msgId This parameter was generated by MyBatis Generator
     * @return 对应的数据记录
     */
    Message selectByPrimaryKey(Integer msgId);

    /**
     * 动态字段，根据主键来更新符合条件的数据记录，t_message
     *
     * @param record 数据记录
     * @return 更新后的数据对象
     */
    int updateByPrimaryKeySelective(Message record);

    /**
     * 根据主键来更新符合条件的数据记录，t_message
     *
     * @param record 数据记录
     * @return 更新后的数据对象
     */
    int updateByPrimaryKey(Message record);

    /**
     * This method was generated by MyBatis Generator，t_message
     *
     * @param record 数据记录
     */
    List<Message> selectByParams(Message record);
}