/**
 * <p> 
 * Copyright (C) IBALIFE Software Co.,Ltd.
 * </p>
 * <p>
 * 创建日期： 2017-11-14
 * </p>
 */
package cn.liuyiyou.web.mapper;

import cn.liuyiyou.web.model.User;
import cn.liuyiyou.web.model.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

/**
 * <code>user</code>的 MyBatis Mapper 接口<br>
 * 对应的数据表为 <code>user</code>
 * <p>
 * 创建日期： 2017-11-14
 * </p>
 */
public interface UserMapper {

    /**
     * 根据指定的条件获取数据记录数，user
     *
     * @param example 动态查询条件
     * @return 符合查询条件的数据记录条数
     */
    int countByExample(UserExample example);

    /**
     * 根据指定的条件删除数据库符合条件的记录，user
     *
     * @param example 动态查询条件
     * @return 删除的数据记录条数
     */
    int deleteByExample(UserExample example);

    /**
     * 根据主键删除数据库的记录，user
     *
     * @param uid This parameter was generated by MyBatis Generator
     * @return 删除的数据记录条数
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * 将数据记录插入数据库，user
     *
     * @param record 数据记录
     * @return 新插入的数据对象
     */
    int insert(User record);

    /**
     * 将数据记录中值不为 <code>null</code> 的字段写入数据库，user
     *
     * @param record 数据记录
     * @return 新插入的数据对象
     */
    int insertSelective(User record);

    /**
     * 根据指定的条件查询符合条件的数据记录，user
     *
     * @param example 动态查询条件
     * @return 查询到的数据记录列表
     */
    List<User> selectByExampleWithRowbounds(UserExample example, RowBounds rowBounds);

    /**
     * 根据指定的条件查询符合条件的数据记录，user
     *
     * @param example 动态查询条件
     * @return 查询到的数据记录列表
     */
    List<User> selectByExample(UserExample example);

    /**
     * 根据指定主键获取一条数据记录，user
     *
     * @param uid This parameter was generated by MyBatis Generator
     * @return 对应的数据记录
     */
    User selectByPrimaryKey(Integer uid);

    /**
     * 动态根据指定的条件来更新符合条件的数据记录，user
     *
     * @param record 数据记录
     * @param example 动态查询条件
     * @return 更新的数据记录条数
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * 根据指定的条件来更新符合条件的数据记录，user
     *
     * @param record 数据记录
     * @param example 动态查询条件
     * @return 更新的数据记录条数
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * 动态字段，根据主键来更新符合条件的数据记录，user
     *
     * @param record 数据记录
     * @return 更新后的数据对象
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * 根据主键来更新符合条件的数据记录，user
     *
     * @param record 数据记录
     * @return 更新后的数据对象
     */
    int updateByPrimaryKey(User record);

    /**
     * This method was generated by MyBatis Generator，user
     *
     * @param record 数据记录
     */
    List<User> selectByParams(User record);
}