/**
 * <p> 
 * Copyright (C) IBALIFE Software Co.,Ltd.
 * </p>
 * <p>
 * 创建日期： 2017-11-17
 * </p>
 */
package cn.liuyiyou.blog.service;

import cn.liuyiyou.blog.entity.Tag;
import com.github.pagehelper.PageInfo;

/**
 * <code>t_tag</code>管理的 DSF 服务接口定义<br>
 * 对应的数据表为 <code>t_tag</code>
 * <p>
 * 创建日期： 2017-11-17
 * </p>
 */
public interface TagService {

    /**
     * This method was generated by MyBatis Generator，t_tag
     *
     * @param record 数据记录
     */
    Tag addTag(Tag record);

    /**
     * This method was generated by MyBatis Generator，t_tag
     *
     * @param id 主键
     */
    Integer delTag(Integer id);


    /**
     * This method was generated by MyBatis Generator，t_tag
     *
     * @param record 数据记录
     */
    Tag updateTag(Tag record);


    /**
     * This method was generated by MyBatis Generator，t_tag
     *
     * @param id 主键
     */
    Tag getByKey(Integer id);


    /**
     * This method was generated by MyBatis Generator，t_tag
     *
     * @param params This parameter was generated by MyBatis Generator
     */
    PageInfo<Tag> selectByParamsWithPage(Tag params);
}