/**
 * <p> 
 * Copyright (C) IBALIFE Software Co.,Ltd.
 * </p>
 * <p>
 * 创建日期： 2017-11-17
 * </p>
 */
package cn.liuyiyou.web.service;

import cn.liuyiyou.web.model.Blog;
import com.github.pagehelper.PageInfo;

/**
 * <code>t_blog</code>管理的 DSF 服务接口定义<br>
 * 对应的数据表为 <code>t_blog</code>
 * <p>
 * 创建日期： 2017-11-17
 * </p>
 */
public interface BlogService {

    /**
     * This method was generated by MyBatis Generator，t_blog
     *
     * @param record 数据记录
     */
    Blog addBlog(Blog record);

    /**
     * This method was generated by MyBatis Generator，t_blog
     *
     * @param id 主键
     */
    Integer delBlog(Integer id);


    /**
     * This method was generated by MyBatis Generator，t_blog
     *
     * @param record 数据记录
     */
    Blog updateBlog(Blog record);

     /**
     * This method was generated by MyBatis Generator，t_blog
     *
     * @param id 主键
     */
    Blog getByKey(Integer id);


    /**
     * This method was generated by MyBatis Generator，t_blog
     *
     * @param params This parameter was generated by MyBatis Generator
     */
    PageInfo<Blog> selectByParamsWithPage(Blog params);


    /**
     * 得到博客以及所带的标签
     * @param params
     * @return
     */
    PageInfo<Blog> selectBlogPageWithTags(Blog params);


}