/**
 * <p>
 * Copyright (C) IBALIFE Software Co.,Ltd.
 * </p>
 * <p>
 * 创建日期： 2017-11-17
 * </p>
 */
package cn.liuyiyou.web.service;

import cn.liuyiyou.web.model.Message;
import com.github.pagehelper.PageInfo;

/**
 * 短消息管理的 DSF 服务接口定义<br>
 * 对应的数据表为 <code>t_message</code>
 * <p>
 * 创建日期： 2017-11-17
 * </p>
 */
public interface MessageService {

    /**
     * This method was generated by MyBatis Generator，t_message
     *
     * @param record 数据记录
     */
    Message addMessage(Message record);

    /**
     * This method was generated by MyBatis Generator，t_message
     *
     * @param id 主键
     */
    Integer delMessage(Integer id);


    /**
     * This method was generated by MyBatis Generator，t_message
     *
     * @param record 数据记录
     */
    Message updateMessage(Message record);


    /**
     * This method was generated by MyBatis Generator，t_message
     *
     * @param id 主键
     */
    Message getByKey(Integer id);


    /**
     * This method was generated by MyBatis Generator，t_message
     *
     * @param params This parameter was generated by MyBatis Generator
     */
    PageInfo<Message> selectByParamsWithPage(Message params);
}